### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by levisteentjes2003** [citizenfx/fivem-docs#139]
hello i have been banned by a hacker and my friends we was playing and there was a hacker coming and he banned me and now i want a unban my name is levi steentjes and to night is a party with my friends
and on discord levi.pdk1#2084 and on fivem levi steentjess and steam levi steentjes
i hope you can unban me from fivem

**Comment by DoJoMan18** [comment]
Hello Levi,

If think that your native language is Dutch so because of that I will answer in Dutch.

Dit is niet de plek waar je dit soort dingen kunt posten. Wanneer je problemen hebt met FiveM / RedM dan kun je het beste een topic op de forums aanmaken. (https://forum.cfx.re/)

Voor jij vraag ligt het eraan waar je gebanned bent. Ik kan/wil je wel verder helpen. Stuur me even een vriendschap verzoek op Discord: DoJoMan18#6799

Zou je daarnaast mijn reactie als oplossing kunnen zetten of in iedergeval de issue sluiten?

Groet,
DoJoMan18
