### ISSUE TITLE
Finish/Improve Dev Docs

### ISSUE THREAD

**Issue by Nimious44** [citizenfx/fivem-docs#231]
The developer documentation is currently incomplete and has very little information, which makes it hard for people to contribute. Finishing them would make it a lot easier.

**Comment by tabarra** [comment]
### Step 1:
![step1](https://i.imgur.com/hyfK3wd.png)

### Step 2:
![step2](https://i.imgur.com/UzeYWy3.png)

**Comment by Nimious44** [comment]
Seeing as there's a limited change of this getting an actual response, might as well close it.

**Comment by AvarianKnight** [comment]
> Seeing as there's a limited chance of this getting an actual response, might as well close it.

Not sure what you mean here, Tabarra gave pretty simple steps.

Documentation is done by the community. If you have anything meaningful to contribute, open up a pull request, technetium will usually respond to it and ask questions, if you change something drastically he'll ask you how you came to find these changes so he can make sure there are no breaking changes to the natives & native gen.

The project lives on community contribution, if no one contributes, the documents will stay the way they are, and then people will come and say 'docs are bad' instead of actually contributing to make them better 🙃
